services:
  - type: web
    name: insertionordersmart
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ORDER_COUNTER_FILE
        value: /var/data/smart1_order_counter.json
      - key: GHL_WEBHOOK_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: BRANDFETCH_API_KEY
        sync: false
      - key: BRANDFETCH_CLIENT_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-5-mini

    disk:
      name: smart1-order-data
      mountPath: /var/data
      sizeGB: 1
